// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Election.Models
{
    public partial class Admin
    {
        public Admin()
        {
            ElectionInfo = new HashSet<ElectionInfo>();
        }

        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }

        public virtual ICollection<ElectionInfo> ElectionInfo { get; set; }
    }
}