// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Election.Models
{
    public partial class District
    {
        public District()
        {
            ElectionInfo = new HashSet<ElectionInfo>();
            Person = new HashSet<Person>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ElectionInfo> ElectionInfo { get; set; }
        public virtual ICollection<Person> Person { get; set; }
    }
}