// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Election.Models
{
    public partial class ElectionInfo
    {
        public ElectionInfo()
        {
            ElectionResult = new HashSet<ElectionResult>();
            ElectionVote = new HashSet<ElectionVote>();
            PersonElection = new HashSet<PersonElection>();
            PositionVote = new HashSet<PositionVote>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int DistrictId { get; set; }
        public int CreateBy { get; set; }

        public virtual Admin CreateByNavigation { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<ElectionResult> ElectionResult { get; set; }
        public virtual ICollection<ElectionVote> ElectionVote { get; set; }
        public virtual ICollection<PersonElection> PersonElection { get; set; }
        public virtual ICollection<PositionVote> PositionVote { get; set; }
    }
}