// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Election.Models
{
    public partial class Person
    {
        public Person()
        {
            ElectionResult = new HashSet<ElectionResult>();
            ElectionVote = new HashSet<ElectionVote>();
            PersonElection = new HashSet<PersonElection>();
            PositionVote = new HashSet<PositionVote>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public int DistrictId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public virtual District District { get; set; }
        public virtual ICollection<ElectionResult> ElectionResult { get; set; }
        public virtual ICollection<ElectionVote> ElectionVote { get; set; }
        public virtual ICollection<PersonElection> PersonElection { get; set; }
        public virtual ICollection<PositionVote> PositionVote { get; set; }
    }
}