// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Election.Models
{
    public partial class Position
    {
        public Position()
        {
            ElectionResult = new HashSet<ElectionResult>();
            PositionVote = new HashSet<PositionVote>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ElectionResult> ElectionResult { get; set; }
        public virtual ICollection<PositionVote> PositionVote { get; set; }
    }
}